require:
 - rubocop-rails
 - rubocop-minitest
 - rubocop-rake

AllCops:
  NewCops: enable
  # 2.0 was dropped in rubocop 0.50
  # TargetRubyVersion: 2.0
  Exclude:
    - gemfiles/*

Rails/RakeEnvironment: { Enabled: false }
Bundler/OrderedGems: { Enabled: false }

Minitest/MultipleAssertions: { Enabled: false }

# maybe later
Style/StringLiterals: { Enabled: false }
Style/Documentation: { Enabled: false }

# we allow older rubies
Gemspec/RequiredRubyVersion: { Enabled: false }

# rails app is for tests
Rails/RenderInline: { Enabled: false }
Rails/ApplicationController: { Enabled: false }

Metrics/BlockLength:
  Exclude:
    - spec/*

Metrics/MethodLength: { Max: 25 }
Metrics/AbcSize: { Enabled: false }
Metrics/CyclomaticComplexity: { Max: 15 }
Metrics/PerceivedComplexity: { Max: 15 }